add mysql service to github action

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -11,6 +11,19 @@ jobs:
     name: Symfony (PHP ${{ matrix.php-versions }})
     # https://hub.docker.com/_/ubuntu/
     runs-on: ubuntu-latest
+
+    # Docs: https://docs.github.com/en/actions/using-containerized-services
+    services:
+      mysql:
+        image: mysql:latest
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_ROOT_PASSWORD: symfony
+          MYSQL_DATABASE: symfony
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
+
     strategy:
       fail-fast: true
       matrix:
@@ -90,6 +103,15 @@ jobs:
         run: |
           php bin/console -V
           php bin/console about
+
+      # Doctrine Database
+      - name: Run Migration
+        run: |
+          composer require --dev symfony/orm-pack
+          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+        env:
+          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+
       # Tests
       - name: Run unit and functional tests
         run: |
